name: "Compare config files"

on: 
  pull_request: 
    types: [opened, reopened]

jobs: 
  Compare:
   name: Compare keys in config-es.json & config.json
   runs-on: ubuntu-latest
   
   steps:
    - name: Checking keys
      uses: amanueltsfy/assets@main