name: 'Compare config files'

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize]

jobs:
  Compare:
    name: Compare keys in config-es.json & config.json
    runs-on: ubuntu-latest

    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Checking config keys
        uses: ./
