name: "Compare config files"

on:
  pull_request:
    branches: [main]

jobs:
  Compare:
    name: Compare keys in config-es.json & config.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: amanueltsfy/assets
          path: main
      - name: Checking keys
        uses: Focus-Bear/assets@main
