name: 'Compare config files'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Compare:
    name: Compare keys in config-es.json & config.json
    runs-on: windows-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          repository: amanueltsfy/assets
          ref: update-schema/notes

      - name: Checking config keys
        uses: ./
