name: "Compare config files"

on:
  pull_request_target:
    branches: [main]

jobs:
  Compare:
    name: Compare keys in config-es.json & config.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Checking keys
        uses: ./
