name: 'Compare config files'

on:
  pull_request_target:
    branches: [main]

jobs:
  Compare:
    name: Compare keys in config-es.json & config.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Checking config keys
        uses: ./
