name: "Compare config files"

on: 
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs: 
  Compare:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compare keys in config-es.json & config.json
      runs-on: ubuntu-latest
   
   steps:
    - name: Checking keys
      uses: ./
