name: Check for NEEDS TRANSLATION

on:
  workflow_dispatch:

jobs:
  check-translation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check config-es.json
        run: |
          if grep -q "NEEDSTRANSLATION" ${{ github.workspace }}/config/config-es.json; then
            echo "config-es.json has items that need translation"
            exit 1
          else
            echo "config-es.json does not need translation"
          fi
